(function(){
  function toggleSection()
  {
      if(location.hash=="#hashtrap")
          document.getElementById("portfolioContent").style.display="block";
      else
          document.getElementById("portfolioContent").style.display="none";
  }
  if(window.addEventListener)
  {
      window.addEventListener("hashchange",toggleSection,false);
      window.addEventListener("load",toggleSection,false);
  }
  else
  {
      window.attachEvent("onhashchange",toggleSection);
      window.attachEvent("onload",toggleSection);
  }
})();